Mengimport Pakage numpy

In [56]:
import numpy

Menambahkan Variable untuk membuat array dengan menggunakan pakage numpy

In [59]:
n = int(input("masukkan jumlah variable yang akan digunakan "))

masukkan jumlah variable yang akan digunakan 3


Menjalankan code untuk membuat array

In [61]:
x = numpy.zeros(n)
SPL = numpy.zeros((n,n+1))

pengguna memasukkan nilai kedalam matrix Memasukkan nilai kedalam array

In [63]:
print("masukkan nilai kedalam array")
for i in range(n):
  for j in range(n+1):
    SPL[i][j]=float(input(f"a[{i}][{j}]"))


masukkan nilai kedalam array
a[0][0]2
a[0][1]3
a[0][2]-1
a[0][3]5
a[1][0]4
a[1][1]4
a[1][2]-3
a[1][3]3
a[2][0]-2
a[2][1]3
a[2][2]-1
a[2][3]1


Melakukan eliminasi gauss

In [64]:
# SPL = ([[2,3,-1,5],[4,4,-3,3],[-2,3,-1,1]]) #ini matriksnya
print("Sistem Persamaan Linear matriks adalah ",SPL)
for j in range(n):
  #Melakukan pengecheckan pada pembagi
  if SPL[j][j] == 0:
    sys.exit('Terdapat nilai 0 pada diagonal utama')

  for k in range(j+1,n):
    # mecari nilai rasio yang digunakan untuk dikalikan dengan baris j
    rasio = SPL[k][j]/SPL[j][j]

    for i in range(n+1):
      # melakukan eliminasi pada baris i
      SPL[k][i] = SPL[k][i] - rasio * SPL[j][i]


SPL

Sistem Persamaan Linear matriks adalah  [[ 2.  3. -1.  5.]
 [ 4.  4. -3.  3.]
 [-2.  3. -1.  1.]]


array([[  2.,   3.,  -1.,   5.],
       [  0.,  -2.,  -1.,  -7.],
       [  0.,   0.,  -5., -15.]])



Melakukan Subtitusi balik untuk mencari nilai akhir variable


In [65]:
# Melakukan Subtitusi balik untuk mencari nilai akhir variable
x[2] = SPL[n-1][n] / SPL[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = SPL[i][n]
    for j in range(i+1,n):
      # melakukan pengurangan pada pada variable yang sudah ditemukan
      x[i] = x[i] - SPL[i][j]*x[j]
    # jika selesai tinggal membagi variable yang dicari dengan nilai akhir
    x[i] = x[i] / SPL[i][i]



print("Nilai x:", x[0])
print("Nilai y:", x[1])
print("Nilai z:", x[2])

Nilai x: 1.0
Nilai y: 2.0
Nilai z: 3.0
